spring:
  server:
    port: 8080

azure:
  subscriptionKey: 1230912
  uriBase: uriBase
  faceAttributes: age,gender,headPose,smile,facialHair,glasses,emotion,hair,makeup,occlusion,accessories,blur,exposure,noise